# Generated by Django 5.0.6 on 2024-06-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBConnection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_comment='Data e hora da criação.')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_comment='Data e hora da última alteração.')),
                ('db_name', models.CharField(max_length=254, unique=True)),
                ('db_user', models.CharField(max_length=254)),
                ('db_password', models.CharField(max_length=254)),
                ('db_host', models.CharField(max_length=254)),
                ('db_port', models.IntegerField(default=5432)),
                ('db_type', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('mariadb', 'MariaDB'), ('sqlserver', 'SQL Server'), ('oracle', 'Oracle'), ('sqlite', 'SQLite')], default='postgresql', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
