# Generated by Django 5.0.6 on 2024-06-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbconnection',
            name='use_ssl',
            field=models.BooleanField(default=False, verbose_name='Usar SSL'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='db_host',
            field=models.CharField(max_length=254, verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='db_name',
            field=models.CharField(max_length=254, unique=True, verbose_name='Base de dados'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='db_password',
            field=models.CharField(max_length=254, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='db_port',
            field=models.IntegerField(default=5432, verbose_name='Porta'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='db_type',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL')], default='postgresql', max_length=30, verbose_name='Selecione o tipo'),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='db_user',
            field=models.CharField(max_length=254, verbose_name='Usuário'),
        ),
    ]
