pipeline:
  identifier: Build_45pbd_dbvizu_1720097992655
  name: Build 45pbd-dbvizu
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.GHcesarfreire
        repoName: 45pbd-dbvizu
  stages:
    - stage:
        name: Build docker image
        identifier: Build_docker_image
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and push
                  identifier: Build_and_push
                  spec:
                    connectorRef: account.harnessImage
                    repo: cesarfreire/dbvizu
                    tags:
                      - latest
